### ISSUE TITLE
mesa plot

### ISSUE THREAD

**Issue by kao25** [rjfarmer/mesaplot#10]
Hi all: 
[examples.tar.gz](https://github.com/rjfarmer/mesaplot/files/1347177/examples.tar.gz)

When i try to compile writing: python3 abundances.py i get error. the path was correct but i did not know where is the issue. 
![screenshot from 2017-10-01 10-09-57](https://user-images.githubusercontent.com/32434122/31055446-dd01912e-a690-11e7-8d47-d736c70bd43f.png)

Thanks for your support

Kao

**Comment by rjfarmer** [comment]
I have no idea why you have these lines in the code:

import mkipp
import kipp_data
import mesa_data
import matplotlib.pyplot as plt
from matplotlib.patches import PathPatch
import numpy as np

Those are completely wrong things to have in this file and i have no idea where you got them from. You have commented out the two lines you actually need:

#import mesaPlot as mp
#import matplotlib.pyplot as plt

should be 
import mesaPlot as mp
import matplotlib.pyplot as plt

ImportError and from the previous issue, FileNotFoundError are basic python error messages, please try to learn some basic python and how to debug these kind of errors

**Comment by kao25** [comment]
Thank you for your response.

Fot the code i just downloaded from the website i did not change anything
and the two lines were commented with #.

I will more check for the errors.

Cheers
Kao
