### ISSUE TITLE
IndexError in _rebinKipqDataNoModInd

### ISSUE THREAD

**Issue by rjfarmer** [rjfarmer/mesaplot#11]
Reported by @kao25 against commit 9227dc8

--------------------------------------------------------------------------------------------------

I downloaded the zip file and changed the LOGS file by my results.
I had 60 columns and 60 000 lines.

When i run the code like plotKip.py i had this kind of error :

Traceback (most recent call last):
File "plotKip.py", line 11, in
p.plotKip(m,fig=fig,ax=ax,show=False)
File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1849, in plotKip
File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1941, in plotKip3
File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 2112, in _getHistBurnData
File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 2149, in _rebinKipqData
File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 2159, in _rebinKipqDataNoModInd
IndexError: list index out of range

How i can fixe that please ?

Thanks

--------------------------------------------------------------------------------------------------

**Comment by rjfarmer** [comment]
Please can you copy into the bug report the exact script you used as well as a link to a online copy of your history file.

Thanks

**Comment by kao25** [comment]
import mesaPlot as mp
import matplotlib.pyplot as plt
m=mp.MESA()
m.loadHistory()
p=mp.plot()

fig=plt.figure(figsize=(12,10))
ax=fig.add_subplot(111)

#Simply plot
p.plotKip(m,fig=fig,ax=ax,show=False)
plt.show()


The link to download history and profile files is here:

https://drive.google.com/open?id=1YoRFLqAs0755WKlVgXZp58LOP9tdeTGx

Thanks

**Comment by rjfarmer** [comment]
Your history file is missing the required fields to plot a kippenhan plot. Please add:
mixing_regions 20
burning_regions 20
To your history_columns.list file and rerun your model.

Commit  6d6475c will now warn you if you are missing these fields.

**Comment by kao25** [comment]
Hi Dr. Farmer:

I used your code to plot the Kippenhahn and as you told me, when i added
the mixing regions20 it works.
However for the abundances and other cases it does not work.

mesa-saa@mesa-dell7000 ~/Downloads/mesaplot3/examples $ python dynamo.py
LOGS//profile58.data
Traceback (most recent call last):
  File "dynamo.py", line 12, in <module>
    p.plotDynamo(m,yrng=[0,10],fig=fig,ax=ax,show_rotation=False)
TypeError: plotDynamo() got an unexpected keyword argument 'yrng'
mesa-saa@mesa-dell7000 ~/Downloads/mesaplot3/examples $ python plotTRho.py
LOGS//profile58.data
Traceback (most recent call last):
  File "plotTRho.py", line 14, in <module>

p.plotTRho(m,fig=fig,ax=ax,show=False,showAll=True,show_burn=True,show_mix=True)
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 2330, in
plotTRho
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1822, in
plotProfile
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1201, in
_plotMultiProf
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 554, in
_plotBurnRegions
ValueError: no field of name net_nuclear_energy
mesa-saa@mesa-dell7000 ~/Downloads/mesaplot3/examples $



What do you advice me to do ?.

Thanks

2017-11-22 2:31 GMT-05:00 Robert Farmer <notifications@github.com>:

**Comment by rjfarmer** [comment]
Hi
Things like this are useful to make a new bug report instead of using a closed one.

For the plotDynamo plot there is an error in the documentation and it should be y1rng not yrng in the p.plotDynamo call.

For the plotTRho error, its telling you what to do:
ValueError: no field of name net_nuclear_energy

Means it can not find the net_nuclear_energy in your profile data, so you wither need to add that to your profile_columns file or remove the show_burn=True option from the p.plotTRho command.

**Comment by kao25** [comment]
Thank you so much it works.

I have two questions please:

1/- for the Kippenhahn plot, i have my own graph but was not able to say
the red color or blue refers to what. where i can read your hole code and
see the details ? On plot.py ?

2/- For both of abundances and dynamo the code does not work, Your
suggestions was* "For the plotDynamo plot there is an error in the
documentation and it should be y1rng not yrng in the p.plotDynamo call." *I
did it and does not work.

LOGS//profile58.data
Traceback (most recent call last):
  File "dynamo.py", line 12, in <module>
    p.plotDynamo(m,yrng=[0,10],fig=fig,ax=ax,show_rotation=False)
TypeError: plotDynamo() got an unexpected keyword argument 'yrng'
mesa-saa@mesa-dell7000 ~/Downloads/mesaplot3/examples $


For the abundances case i have this error;

Traceback (most recent call last):
  File "abundances.py", line 9, in <module>
    m.loadHistory()
  File "build/bdist.linux-x86_64/egg/mesaPlot/file_reader.py", line 171, in
loadHistory
  File "build/bdist.linux-x86_64/egg/mesaPlot/file_reader.py", line 87, in
loadFile
  File "build/bdist.linux-x86_64/egg/mesaPlot/file_reader.py", line 114, in
_filelines
IOError: [Errno 2] No such file or directory: 'examples/LOGS/history.data'



I do not have this path:  'examples/LOGS/history.data'  I tried to find it
on the directory but without any success.


Thanks for your help !


2017-11-24 4:19 GMT-05:00 Robert Farmer <notifications@github.com>:

**Comment by rjfarmer** [comment]
1) So for the color scheme of a kip plot the red on the colorbar is net energy generation from nuclear burning (purple shows energy loss from neutrinos). For the other colors those are different types of mixing if you have show_mix_labels=True in the plotKip command then you will get a legend along the left y axis.

2) You haven't done anything, the error message is the same as the one before and still shows you have yrng not y1rng in the function call

3) You wont, as that is the path to the data files in this repository not your mesa work directory.  There should be a line with m.log_fold = , this should be altered to point toy your LOGS folder not the one in the examples.

**Comment by kao25** [comment]
I have an issue from two weeks and could not solve it.

https://github.com/rjfarmer/mesaplot  case of: Kippenhan plot with star age
vs mass

when i run it: i have this kind of error:

#PLOT 1
oFHersheySerif
Tlx mesaPlot as mp
Tlx matplotlib.pyplot as plt
plot: an unrecognized command `0xa' was encountered in the input
plot: the input file `plotKip.py' could not be parsed


Do you have any advice for me

Thanks

2017-11-27 5:15 GMT-05:00 Robert Farmer <notifications@github.com>:

**Comment by rjfarmer** [comment]
Please, create a new issue when reporting a different error, you've been asked before. 

You also need to show what your doing preferably by copying the while code or linking to the file online that you are trying to run. What you have copied in does not make sense on its own and is not enough to diagnose your problem.
