### ISSUE TITLE
Changing parametrs

### ISSUE THREAD

**Issue by sena2703** [rjfarmer/mesaplot#12]
Hi:

I would like to thank Dr. Farmer for giving us this great tool, it helps me a lot !

I have two questions:

About the Kippenhahn diagrams: Is it possible to change the label (sign(eps_nuc .....) How i can delete and make the helium abundance or other element ? In other words having a Kipp plot withount nuclear burning regions.

Second question about HR diagram, i copied the code on the GitHub page but i how i change the settings: make big scale, change color ...

Thanks
Abdel

**Comment by rjfarmer** [comment]
To change what the colorbar shows look at the plotKip3 example:

p.plotKip3(m,plot_type='profile',xaxis='model_number',yaxis='mass',zaxis='logRho',mod_min=1,mod_max=3000)

so to switch to he abundance then you need to change the zaxis to 'he4'. Note though you'll need a lot of profile files to make it look good, the other kippenhahn's use history data which is easier to have alot of.

for the hr plot if you need to make changes to the plot you best bet is just to write your own version, where you can then control all the different plotting parameters
