### ISSUE TITLE
Kipp plots

### ISSUE THREAD

**Issue by kao25** [rjfarmer/mesaplot#13]
Hi all: we can read more about 
I am trying to plot Kippenhahn plots but (Mass VS age or time).

I took the code from:
https://github.com/rjfarmer/mesaplot

If we go down under a section Kippenhahns we can see many examples, so i created a new text file and past the following: 

import mesaPlot as mp
m=mp.MESA()
p=mp.plot()
m.loadHistory()
p.plotKip2(m)
My question is how to plot a kipp plot : Mass VS Age   

[test.txt](https://github.com/rjfarmer/mesaplot/files/1580220/test.txt)

#PLOT 1
oFHersheySerif
Tlx mesaPlot as mp
Tlx matplotlib.pyplot as plt
plot: an unrecognized command `0xa' was encountered in the input
plot: the input file `plotKip.py' could not be parsed

Thanks
Kao

**Comment by rjfarmer** [comment]
>#PLOT 1
>oFHersheySerif
>Tlx mesaPlot as mp
>Tlx matplotlib.pyplot as plt
>plot: an unrecognized command 0xa' was encountered in the input plot: the input fileplotKip.py' could not be parsed

Thats not valid python see the Tlx at the start of the lines and the line with oFHersheySerif. It  might be a copy/paste error but you need to send *your* code not my code as a file
