### ISSUE TITLE
codes running

### ISSUE THREAD

**Issue by zabana31** [rjfarmer/mesaplot#14]
Hello guys:

I have 2 questions:

I used the KIpps plot and worked perfectly, but the only issue is for the section plotting: 

The error concerning the abundances.py
********
Traceback (most recent call last):
  File "abundances.py", line 9, in <module>
    m.loadHistory()
  File "build/bdist.linux-x86_64/egg/mesaPlot/file_reader.py", line 171, in loadHistory
  File "build/bdist.linux-x86_64/egg/mesaPlot/file_reader.py", line 87, in loadFile
  File "build/bdist.linux-x86_64/egg/mesaPlot/file_reader.py", line 114, in _filelines
IOError: [Errno 2] No such file or directory: '/home/ibiza/mesaplot-master/examples/LOGS/history.data'
********
The code for the abundances:

#import mesaPlot as mp
import matplotlib.pyplot as plt
m=mp.MESA()
m.log_fold='/home/ibiza/mesaplot-master/examples/LOGS/'
m.loadHistory()
m.loadProfile(num=-1)
p=mp.plot()
#Simply plot
p.plotAbun(m)
#Advanced
fig=plt.figure(figsize=(12,12))
ax=fig.add_subplot(111)
p.plotAbun(m,num_labels=6,rand_col=True,y1rng=[-6.5,0.5],show_title_model=True,show_title_age=True,fig=fig,ax=ax,
xmax=5.0)
# Abundace as function of atomic mass
fig=plt.figure(figsize=(12,12))
ax=fig.add_subplot(111)
p.plotAbunByA(m,mass_range=[0.0,5.0],fig=fig,ax=ax)

# Abundance as a function of proton and neutron number
fig=plt.figure(figsize=(12,12))
ax=fig.add_subplot(111)
p.plotAbunPAndN(m,mass_range=[0.0,5.0],mass_frac_rng=[10**-5,1.0],fig=fig,ax=ax).

Under the section Plotting we have : History data and It contains this code:  
*******
import mesaPlot as mp
m=mp.MESA()
p=mp.plot()
m.loadHistory()
p.plotHistory(m,xaxis='star_age',y1='log_center_T',y2='he_core_mass')

********

I paste it in a text file and when i run it, i got a good plot but i can not change anything, no colors or scale.

How i can do it ? and can we save the plots on a pdf or JPEG because i did not saw save button
![age](https://user-images.githubusercontent.com/35209959/34658750-7f62f30c-f3ff-11e7-903c-ad72f21cd946.png)

Thanks so much for sharing with the community this tools.

Best regards
Zabana

**Comment by rjfarmer** [comment]
>IOError: [Errno 2] No such file or directory: '/home/ibiza/mesaplot-master/examples/LOGS/history.data'

The first error says that it cant find the history data specified by the path set in m.log_fold
m.log_fold='/home/ibiza/mesaplot-master/examples/LOGS/'

Check that '/home/ibiza/mesaplot-master/examples/LOGS/' is where you are storing your history data

On the second question, if you look in mesaplot/plot.py and search for plotHistory you will see the function can take many arguments. Things like y1col and y2col will set the line colours, xmin/xmax set the x axis scale while y1rng=[] sets the y1 axis limits. 

To save the plot either in the plot window that pops up click the icon that looks like a floppy disk or modify your plot code like so:

````python
import mesaPlot as mp
import matplotlib.pyplot as plt

m=mp.MESA()
p=mp.plot()
m.loadHistory()
fig=plt.figure()
ax=fig.add_subplot(111)
p.plotHistory(m,xaxis='star_age',y1='log_center_T',y2='he_core_mass',fig=fig,ax=ax)
fig.savefig('output.jpeg')
````

**Comment by zabana31** [comment]
For the abundance: after verifying each parameter i had this issue:
**************************************************************************
/home/ibiza/mesaplot-master/examples/LOGS//profile50.data
Traceback (most recent call last):
  File "abundances.py", line 14, in <module>
    p.plotAbun(m)
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1329, in plotAbun
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1248, in _plotMultiProf
UnboundLocalError: local variable 'i' referenced before assignment
************************************************


For the scale in order to plot HR or other types of Kipps plot: I looked in mesaplot/plot.py and searched for plotHistory : 

***************************************************************
y1label=y1label,title=title,show_shock=show_shock,show_burn_labels=show_burn_labels,show_mix_labels=show_mix_labels,
							show_mix_line=show_mix_line,show_burn_line=show_burn_line,show_mix_x=show_mix_x,show_burn_x=show_burn_x,
							y2=y2,y2rng=y2rng,fy2=fy2,y2Textcol=y2Textcol,y2label=y2label,y2rev=y2rev,y2log=y2log,y2col=y2col,xlog=xlog,xrev=xrev)
	
	def plotHistory(self,m,xaxis='star_age',y1='star_mass',y2=None,show=True,
					ax=None,xmin=None,xmax=None,xlog=False,y1log=False,y1rng=[None,None],
					y2log=False,y1col='b',y2col='r',minMod=0,maxMod=-1,xrev=False,
					y1rev=False,y2rev=False,points=False,xlabel=None,y1label=None,
					y2label=None,fig=None,y2rng=[None,None],
					fx=None,fy1=None,fy2=None,show_core=False,y1Textcol=None,y2Textcol=None,
					show_title_name=False):
		
		list_y=[y1]
		
		self._plotMultiHist(m,list_y=list_y,show=show,ax=ax,xaxis=xaxis,
							xmin=xmin,xmax=xmax,y1rng=y1rng,y1log=y1log,
							xlabel=xlabel,points=points,
							fig=fig,fx=fx,fy=fy1,minMod=minMod,maxMod=maxMod,annotate_line=False,
							show_title_name=show_title_name,show_core=show_core,
							y2=y2,y2rng=y2rng,fy2=fy2,y2Textcol=y2Textcol,y2label=y2label,y2rev=y2rev,y2log=y2log,y2col=y2col,xlog=xlog,xrev=xrev)	


*********************************************
I tried many combinations in order to change the scale but maybe i'm wrong, is this the part you told me about ? 
![rrrrrrrrr](https://user-images.githubusercontent.com/35209959/34701935-f9c628ee-f4b8-11e7-8bfc-b6d38e304d86.png)


I have added a kip plot but i don t see a floppy disk in order to save the plot.

Thanks

**Comment by rjfarmer** [comment]
For the first issue, can you please attach both the plot commands you are running plus the profile file you are trying to plot

For changing the scales, yes that is thing to do. Again can you show the exact plot commands you are trying. To alter the kip plots you will need to search for plotKip and look at the parameters that function takes.

For saving the plot, you should have a window pop up once the plot completes. Follow the instructions here https://matplotlib.org/users/navigation_toolbar.html on how to navigate this window and save a file

**Comment by zabana31** [comment]
On the GitHub website there is some codes in order to call the routine. 
I copy and past the code on text file and run it. For HR diagram i coy and past this one:

import mesaPlot as mp
m=mp.MESA()
p=mp.plot()
m.loadHistory()
p.plotHR(m)


For Kipp plots:

import mesaPlot as mp
m=mp.MESA()
p=mp.plot()
m.loadHistory()
p.plotKip2(m)


Abundances:

import mesaPlot as mp
m=mp.MESA()
p=mp.plot()
m.loadProfile(num=-1)
p.plotAbun(m)


All the plots i have i can not save them because no floppy disk appear only in one because i download it directly from Github and it is on: mesaplot/examples the file is plotKip.py 
![hr](https://user-images.githubusercontent.com/35209959/34742916-f186d708-f555-11e7-8826-2f818a33c487.png)
![rrrrrrrrr](https://user-images.githubusercontent.com/35209959/34742917-f19814d2-f555-11e7-98ea-a53aa10ad75f.png)

**Comment by rjfarmer** [comment]
When the plot appears (it does appear on screen right?) Please take a screen shot and post here.

**Comment by zabana31** [comment]
this exactly what i see. no thing appear on screen right
![kipp](https://user-images.githubusercontent.com/35209959/34824962-94349fa0-f69e-11e7-8a49-de1bace1f9a9.jpeg)
![hr](https://user-images.githubusercontent.com/35209959/34824964-9614ad88-f69e-11e7-81a9-536e943753fa.png)

**Comment by rjfarmer** [comment]
It sounds like you have a problem with your matplotlib installation, that i cant help you with.

**Comment by zabana31** [comment]
Thank you for your advice. i will try to re install matplotlib. 

I want just to make sure: why i am having this problem, is it due to my profiles ? 

This is the code i am using to plot the abunadances.

import mesaPlot as mp
import matplotlib.pyplot as plt


m=mp.MESA()

m.log_fold='/home/ibiza/MESA DATAS/mesaplot-master/examples/LOGS/'

m.loadHistory()
m.loadProfile(num=-1)
p=mp.plot()

#Simply plot
p.plotAbun(m)

#Advanced
fig=plt.figure(figsize=(12,12))
ax=fig.add_subplot(111)
p.plotAbun(m,num_labels=6,rand_col=True,y1rng=[-6.5,0.5],show_title_model=True,show_title_age=True,fig=fig,ax=ax,
xmax=5.0)


# Abundace as function of atomic mass
fig=plt.figure(figsize=(12,12))
ax=fig.add_subplot(111)
p.plotAbunByA(m,mass_range=[0.0,5.0],fig=fig,ax=ax)

# Abundance as a function of proton and neutron number
fig=plt.figure(figsize=(12,12))
ax=fig.add_subplot(111)
p.plotAbunPAndN(m,mass_range=[0.0,5.0],mass_frac_rng=[10**-5,1.0],fig=fig,ax=ax)




*****************************************************************
The error i have:
**************************************************************
/home/ibiza/MESA DATAS/mesaplot-master/examples/LOGS//profile53.data
Traceback (most recent call last):
  File "abundances.py", line 14, in <module>
    p.plotAbun(m)
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1329, in plotAbun
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1226, in _plotMultiProf
  File "build/bdist.linux-x86_64/egg/mesaPlot/plot.py", line 1053, in _plotAnnotatedLine
  File "/home/ibiza/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 3346, in set_yscale
    ax.yaxis._set_scale(value, **kwargs)
  File "/home/ibiza/.local/lib/python2.7/site-packages/matplotlib/axis.py", line 711, in _set_scale
    self._scale = mscale.scale_factory(value, self, **kwargs)
  File "/home/ibiza/.local/lib/python2.7/site-packages/matplotlib/scale.py", line 553, in scale_factory
    return _scale_mapping[scale](axis, **kwargs)
  File "/home/ibiza/.local/lib/python2.7/site-packages/matplotlib/scale.py", line 242, in __init__
    "{!r}".format(kwargs))
ValueError: provided too many kwargs, can only pass {'basex', 'subsx', nonposx'} or {'basey', 'subsy', nonposy'}.  You passed {'nonposx': 'clip'}

I have added some lines to history column list also:
  mixing_regions 20
      burning_regions 20
      mix_relr_regions 20


Thanks

**Comment by rjfarmer** [comment]
So i just had the same issue you had with the plot not having a save button, i fixed it for me by installing a different matplotlib backend https://matplotlib.org/faq/usage_faq.html#what-is-a-backend and setting up my matplotlibrc to use that over the default. This may work for you.

>ValueError: provided too many kwargs, can only pass {'basex', 'subsx', nonposx'} or {'basey', 'subsy', nonposy'}. You passed {'nonposx': 'clip'}

Looks like maybe you have an old version of matplotlib, what is the output of:

````python
import matplotlib
matplotlib.__version__
````

**Comment by zabana31** [comment]
I have this version: 
matplotlib.__version__
'2.1.1'

I delete it yesterday and install aother version which is 2.1.1
