### ISSUE TITLE
setup.py can't read README.md, UTF-8 vs. ascii issue

### ISSUE THREAD

**Issue by pmartens53** [rjfarmer/mesaplot#15]
Dear Mr. Farmer,

I am trying to install mesaPlot on my Macbook Pro, OS 10.12.6 (Sierra).  I get the following error message:

[petrus-martenss-macbook-pro:~/Desktop/MESA/mesaplot-master] martens% make
python3 setup.py install --user
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    long_description=read('README.md'),
  File "setup.py", line 7, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
make: *** [all] Error 1

I checked the encoding of the file README.dm: it is UTF-8, and it seems setup.py expects ascii.
I tried to convert README.dm to ascii, but produces an error as well:

[petrus-martenss-macbook-pro:~/Desktop/MESA/mesaplot-master] martens% iconv -f UTF-8 -t us-ascii README.md 
iconv: README.md:1:0: cannot convert

Can you help?

Thanks you very much,

Best regards,

Piet Martens

**Comment by rjfarmer** [comment]
For now you should be able to just comment out the long_description line while I look into the file encoding issue.

**Comment by rjfarmer** [comment]
Hi
Can you try d82c6bd and see if that works
Thanks
