### ISSUE TITLE
Kippenhan in radius

### ISSUE THREAD

**Issue by lbugnet** [rjfarmer/mesaplot#20]
Hello,

I am having an issue when trying to represent the Kippenhan diagram in radius instead of mass.
I understand that I have to add "burn_relr_regions 40" inside the history_columns.list file, but it seems to me that MESA doesn't recognise the burn_relr_regions parameter in the history_columns.list file, and returns:

bad history list name: burn_relr_regions
bad history list name: 40

Do you have an idea to solve this issue ?
Thank you very much

## Specifications
  - Version:Release 11554 - Mesa

**Comment by rjfarmer** [comment]
To have burn_relr_regions you need a newer MESA release (12115) as the burn_relr_regions was missing before then.

**Comment by lbugnet** [comment]
Thank you very much it works !
