### ISSUE TITLE
Array index out of bounds when generating Kippenhahn plot

### ISSUE THREAD

**Issue by KTemmink** [rjfarmer/mesaplot#21]
## Expected Behavior
Using the syntax from the documentation to read in the history.data file for a 1Msun star, I tried making a Kippenhahn plot. The code I used (Python 3.7):

```
import mesaPlot as mp
fig,ax = plt.subplots(figsize=(7.5*1.5,7.5))

m=mp.MESA()
m.loadHistory(f='M_1.0/LOGS1/')

p=mp.plot()


p.plotKip3(m,cmin=-1,cmax=7.5,show_mix=True, age_lookback=True, cbar_label=r'$\log\epsilon_{\rm burn}$',show_mass_loc=True, xaxis='star_age', fig=fig,ax=ax,show=False)

plt.show()
```

## Actual Behavior
One of the indices seems to be out of bounds. The exact error message I get is:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-79f5c25f411a> in <module>
     
     17     # p.plotKip3(m,xaxis='star_age',age_lookback=True,age_log=True)
---> 18     p.plotKip3(m,cmin=-1,cmax=7.5,show_mix=True, age_lookback=True, cbar_label=r'$\log\epsilon_{\rm burn}$',show_mass_loc=True, xaxis='star_age', fig=fig,ax=ax,show=False)
     19 
     20     ax.set_ylim((0,ax.get_ylim()[1]))

/usr/local/lib/python3.7/dist-packages/mesaPlot-0.0-py3.7.egg/mesaPlot/plot.py in plotKip3(self, m, plot_type, xaxis, yaxis, zaxis, xmin, xmax, mod_min, mod_max, yrng, xstep, xlabel, ylabel, title, show, reloadHistory, ax, fig, show_mix, mix, show_burn, show_outer_mass, cmin, cmax, cmap, colorbar, cbar_label, show_mass_loc, show_mix_labels, mix_alpha, age_lookback, age_log, age_reverse, age_units, end_time, age_zero, y2, y2rng, mod_index, zlog, zone_frac, num_zones, mix_hatch, hatch_color, zaxis_norm, yaxis_norm, zaxis_contour, zaxis_levels, y1log, dbg)
   2093             if show_burn:
   2094                 data_z=self._getHistBurnData(m,data_x,data_y,modInd,burn_prefix,radius)
-> 2095                 data_z=self._rebinKipDataX(data_z,data_x[modInd],lin_x)
   2096                 if dbg:
   2097                     print(np.nanmin(data_z),np.nanmax(data_z))

/usr/local/lib/python3.7/dist-packages/mesaPlot-0.0-py3.7.egg/mesaPlot/plot.py in _rebinKipDataX(self, data, x, lin_x, nan, nan_value)
   2473         ind=np.searchsorted(x,lin_x,sorter=sorter,side='left')
   2474 
-> 2475         data=data[sorter[ind],:]
   2476         if nan:
   2477             data[data<nan_value]=np.nan

IndexError: index 8711 is out of bounds for axis 0 with size 8711
```

## Steps to Reproduce the Problem

  1. Download attached history.data file in .zip
  2. Adapt the provided code to read in said file 
  3. Run the code

## Specifications

  - Version: master
  - Platform: Python 3.7, Jupyter lab, ubuntu 19.04

## Link to history/profile file(s)

[history.zip](https://github.com/rjfarmer/mesaplot/files/4315272/history.zip)

**Comment by rjfarmer** [comment]
Okay so normal Kippenhan's (plotKip) work, the minimal example needed to cause the error is
```
p.plotKip3(m,xaxis='star_age',age_lookback=True)
```
The problem is that the final few timesteps are ~10^-13s but the star is ~10Gyr. We try to compute the age for each model number in the star, we try adding 10^-13s to 10Gyr which is 10Gyr. Even doing it in quad precision, we can not resolve the difference in age between two models. This is then what causes issues for the code

While i work on a better fix, a temporary solution is to limit the models plotted:
```
p.plotKip3(m,xaxis='star_age',age_lookback=True,mod_max=18155)
```
Works for me, and you only lose the last 15 models.

**Comment by KTemmink** [comment]
Thanks for the quick reply! My apologies for not stating explicitly that values in  `star_age` were the problem. The proposed temporary solution works for me too. A possible general solution could be to include something along the lines of 

```
age = m.hist.data['star_age']
idx_max = np.where(age[:-1] != age[1:])[0][-1]
```

and use that to set the maximum model number or range of `data_x`.
