### ISSUE TITLE
Docs directory missing?

### ISSUE THREAD

**Issue by demink** [rjfarmer/mesaplot#22]
## Expected Behavior
The README.md has links, for example to  “More on history plots”.  This should be opening  https://github.com/rjfarmer/mesaplot/blob/master/docs/history.md

## Actual Behavior

Clicking the link gives a 404 error.     It looks like the docs file  and its content are not part of the repo. 

## Steps to Reproduce the Problem

  1. go to online version of Readme.md 1 as shown on https://github.com/rjfarmer/mesaplot
  1. click on link “More on history plots”  (or any of the others)
  
## Specifications

  - Platform: Mac, using Chrome

**Comment by rjfarmer** [comment]
Yeah i forgot to remove the links to the doc pages when i merged them into the main Readme. Fixed in 02a17d9
