### ISSUE TITLE
pip install can't find unittest

### ISSUE THREAD

**Issue by warrickball** [rjfarmer/mesaplot#24]
## Description of problem

I just tried to install [`tulips`](https://astro-tulips.readthedocs.io/) and encountered this error when I tried to `pip install` it:
```
$ python3 -m pip install astro-tulips --user
...
ERROR: Could not find a version that satisfies the requirement unittest (from mesaPlot>=1.1.0->astro-tulips) (from versions: none)
ERROR: No matching distribution found for unittest (from mesaPlot>=1.1.0->astro-tulips)
```
I confirmed that the error is because `mesaPlot` requires `unittest`:
```
$ python3 -m pip install mesaPlot --user
...
ERROR: Could not find a version that satisfies the requirement unittest (from mesaPlot) (from versions: none)
ERROR: No matching distribution found for unittest (from mesaPlot)
```
as appears in `setup.cfg`:
https://github.com/rjfarmer/mesaplot/blob/c466e8862217995859f4d5671afc8d3f138347e5/setup.cfg#L34

I presume the problem is that `unittest` is part of the standard library and not available via PyPI.

I was able to workaround this by installing with `--no-deps` and installing the other dependencies manually where necessary.

## Steps to Reproduce the Problem

  1. `python3 -m pip install mesaplot --user`

## Specifications

  - Versions: mesaPlot 2.0.0, Python 3.9.7
  - Platform: Fedora 33

PS: I hope my issue is sufficiently clear without following the template...

**Comment by rjfarmer** [comment]
There should be a new version of mesaplot on pypi now that fixes this
