### ISSUE TITLE
Wrong axes titles

### ISSUE THREAD

**Issue by SAMUTH3108** [rjfarmer/mesaplot#29]
For the following code to do a TRho plot,

import mesaPlot as mp
import matplotlib.pyplot as plt

m=mp.MESA()
p=mp.plot()
m.loadHistory(f='/lupus2/muthu/mesa_models/m128/20MO/LOGS/')

p.plotHistory(m,xaxis='log_center_Rho', y1='log_center_T')
plt.show()

in the output: i should get the axes titles as log10Tc and log10Rhoc rather i get log10Teff  and log10Rho instead, how do i resolve this
<img width="977" alt="Screenshot 2024-07-09 at 13 16 19" src="https://github.com/rjfarmer/mesaplot/assets/174608963/2c3e6b62-b33a-40c4-bc55-8007be5f2052">

**Comment by rjfarmer** [comment]
plotHistory does not adjust the labels when you change columns. Instead it accepts an xlabel and y1label options which you can set to the text you want.

**Comment by Xenos3108** [comment]
Okay after adding those comments in the label comes out as 'Rho' but not its symbol like i expected and the ylabel doesnt seem to change at all 
input:import mesaPlot as mp
import matplotlib.pyplot as plt


m=mp.MESA()
p=mp.plot()
m.loadHistory(f='/lupus2/muthu/mesa_models/m128/20MO/LOGS/')

p.plotHistory(m,xaxis='log_cntr_Rho', y1='log_cntr_T',xmin=-5,xmax=10,y1rng=[5.65,10.0],xlabel='$log Rho_c$' ,y1label='$log_10_T_c$')
plt.show()

<img width="977" alt="Screenshot 2024-07-09 at 22 55 05" src="https://github.com/rjfarmer/mesaplot/assets/174608963/5de14f34-927e-41ee-ba0d-b0e0aabdf021">

**Comment by SAMUTH3108** [comment]
Okay i was able to change the xlabel but the ylabel doesnt seem to change at all
import mesaPlot as mp
import matplotlib.pyplot as plt


m=mp.MESA()
p=mp.plot()
m.loadHistory(f='/lupus2/muthu/mesa_models/20Mo_test2/LOGS/')
#fig=plt.figure(figsize=(12,10))
#ax=fig.add_subplot(111)


#Simply plot
p.plotHistory(m,xaxis='log_center_Rho', y1='log_center_T',y1rng=[5.65, 10.0],xmin=-5.0,xmax=10.0,xlabel=r'$\log \rho_c$',y1label=r'$\log_{10} \T_c$')#show=True,showAll=True,show_mix=False)
plt.show()

***Ignore the labels on the plot**

<img width="977" alt="Screenshot 2024-07-10 at 11 14 25" src="https://github.com/rjfarmer/mesaplot/assets/174608963/a4f4ff5d-8e9f-4ff2-9f3e-649e129f7be5">

**Comment by rjfarmer** [comment]
Try passing in your own axes

````python
fig=plt.figure(figsize=(12,10))
ax=fig.add_subplot(111)

p.plotHistory(m,fig=fig,ax=ax,show=False)

ax.set_ylabel('some text')
plt.show()
````

**Comment by SAMUTH3108** [comment]
i tried the above didnt seem to work at all, although i did try doing it using mesa reader and it worked fine, ill attach the code down just in case its ever needed in future and thank you for your help!
import mesaPlot as mp
import matplotlib.pyplot as plt
import mesa_reader as mr

T_cRho_c=mr.MesaData("/../../../../../../../../LOGS/history.data")

fig,(ax1) = plt.subplots(figsize=(12,10))
#ax1.set_xticklabels([]);
ax1.set_xlabel(r'$\log \rho_c$')
ax1.set_ylabel(r'$\log T_c$')
ax1.plot(T_cRho_c.log_center_Rho,T_cRho_c.log_center_T,color='black')

output:
<img width="1061" alt="Screenshot 2024-07-11 at 16 17 51" src="https://github.com/rjfarmer/mesaplot/assets/174608963/f19cc9b0-a1c4-4e32-9626-007579ef3a83">
