### ISSUE TITLE
Issue with AbunPandN plot movie compilation

### ISSUE THREAD

**Issue by SAMUTH3108** [rjfarmer/mesaplot#30]
Hello, 

i am trying to do a movie on how the nuclear chart changes until core collapse , the issue is the log10Mass Frac range coloyr bar keeps plotting infinitely 

this is my code : 
import numpy as np
from matplotlib.animation import FuncAnimation, FFMpegWriter
import matplotlib.pyplot as plt
import mesaPlot as mp
import time

# Get current time
current_time = time.strftime("%d%m%Y-%H%M%S")

# Initialize MESA object and plot object
m = mp.MESA()
m.log_fold = '/lupus2/muthu/mesa_models/varyingZ/Z-A21-2/Z=1d-5/LOGS/'
m.loadHistory()
p = mp.plot()

title = 'Abun'  # Provide a descriptive title for the plot
model = 1  # Model number of interest (to start)
max_mass = 20

# Reinitialize MESA object with specific path
m = mp.MESA()
m.log_fold = '/lupus2/muthu/mesa_models/varyingZ/Z-A21-2/Z=1d-5/LOGS/'

fig, ax = plt.subplots(figsize=(25, 12))

# Animation function
def animate(i): 
    number = i + model
    ax.clear()
    m.loadProfile(prof = number)
    p.plotAbunPAndN(m, mass_range=[0.0, 5.0], fig=fig, ax=ax,title=str(number))
    return p

# Create the animation
ani = FuncAnimation(fig, animate, interval = 40, blit = False, repeat = True, frames = 470)

# Save the animation using FFMpegWriter
Writer = FFMpegWriter(fps = 5, metadata = dict(artist='Me'), bitrate = 1800)
ani.save("testNCM.mp4", dpi = 300, writer = Writer)

plt.show()

and this is my output: 

https://github.com/user-attachments/assets/818c62ec-f3f0-4956-8159-2ecd585dd6e7

**Comment by SAMUTH3108** [comment]
NOTE: the original code had 

p.plotAbunPAndN(m, mass_range=[0.0, 5.0], mass_frac_rng=[10**-5, 1.0], fig=fig, ax=ax,title=str(number))

removing mass_frac_rng didnt change the output

**Comment by rjfarmer** [comment]
Instead of ax.clear try plt.clf() as the colorbar is generated with fig.colorbar() so i think you need to clear the figure to stop the extra colorbars.

**Comment by SAMUTH3108** [comment]
worked thnx!
