### ISSUE TITLE
axes title for kippenhahn

### ISSUE THREAD

**Issue by SAMUTH3108** [rjfarmer/mesaplot#31]
Hey,

I have been trying to produce kippenhahn plots with only their convective zones, so I used 'show_burn = False ' command but for some reason I get this error with the plot having no axes title for the x axes ( which should be log10(tau_cc-tau), this is the code

m=mp.MESA()
p=mp.plot()

m.loadHistory(f = "/lupus2/muthu/mesa_models/A21/Zo/LOGS/")
p.plotKip3(m,show_mass_loc=True,age_log=True,yrng=[0,20.0],
           mod_max=6000, mod_min=0, age_lookback=True, xaxis='star_age', 
           show_burn=False, show_mix_labels=False)

![Screenshot 2024-10-29 at 16 48 58](https://github.com/user-attachments/assets/ec3837f0-a479-4cf2-8060-55e844fd9f1f)
 
this is the plot with show burn turned true,
![image](https://github.com/user-attachments/assets/3704b103-2a28-469d-96f9-342beca1c3cc)

**Comment by rjfarmer** [comment]
Can you give 683a615 a try and see if it fixes things for you?

**Comment by SAMUTH3108** [comment]
It worked, Thanks!
