### ISSUE TITLE
Incorrect mass location in Kippenhahn plots

### ISSUE THREAD

**Issue by SAMUTH3108** [rjfarmer/mesaplot#32]
mass loc labels on the Kppenhahn seems to be plotting invalid when xaxis is plotted in terms of core collapse, but when plotted under model number the issue doesn't seem to occur.
Kippenhahn with log(acc-t)/yr
code:
plotter.plotKip3(mesa,show_mass_loc=True,age_log=True,yrng=[0.0, 12.0],mod_max=2900,mod_min=0,age_lookback=True,
    xaxis='star_age',show_burn=True,show_mix_labels=False)
output: 
![KipCC](https://github.com/user-attachments/assets/d9a99d24-356c-4449-a6d0-f6d33d4e4cc0)

Kippenhahn with model number
code:
plotter.plotKip3(mesa,show_mass_loc=True,mod_max=96000,show_burn=True,yrng=[0.0, 12.0])
output
![Kip](https://github.com/user-attachments/assets/8995e1cc-4816-4d91-9a9c-624f8e85de17)

Need the plot in terms of log(tcc-t) but mass loc labels are plotted wrong

**Comment by rjfarmer** [comment]
Can you try 4fee8c7d2 ?

If that doesn't work please share the history file your using

**Comment by SAMUTH3108** [comment]
Yes! the update works, Thank You!
