### ISSUE TITLE
Bug in _listAbun() function 

### ISSUE THREAD

**Issue by OriolAbril** [rjfarmer/mesaplot#4]
I checked how did _listAbun() worked trying to sort out issue #3 and i came across the following problem:
```
>>> p._listAbun(m.hist,prefix='center_')
['center_h1', 'center_he4', 'center_c12', 'center_n14', 'center_o16', 'center_ne20', 
'center_si28', 'center_s32', 'center_ar36', 'center_ca40', 'center_ti44', 'center_ti50', 
'center_ti52', 'center_cr48', 'center_cr54', 'center_cr56', 'center_fe52', 'center_fe54', 
'center_fe56', 'center_fe58', 'center_fe60', 'center_ni56', 'center_ni58', 'center_ni60', 
'center_ni62', 'center_ni64', 'center_zn68', 'center_ge72']
>>> p._listAbun(m.hist,prefix='surface_')
['surface_he4', 'surface_c12', 'surface_n14', 'surface_o16', 'surface_c13', 'surface_o17', 
'surface_o18', 'surface_f19', 'surface_e4', 'surface_e20', 'surface_i28', 'surface_r36', 
'surface_a40', 'surface_i44', 'surface_i50', 'surface_i52', 'surface_r48', 'surface_r54', 
'surface_r56', 'surface_e52', 'surface_e54', 'surface_e56', 'surface_e58', 'surface_e60', 
'surface_i56', 'surface_i58', 'surface_i60', 'surface_i62', 'surface_i64', 'surface_n68', 
'surface_e72']
```
As it can be seen, my file has both surface_element and center_element columns and getting the ones with prefix "center_" gives no problem but when the prefix is surface, the second letters of the elements that have two letters and its atomic mass are taken as an element ('e4' for 'he4', 'e20' for 'ne20'...).

Is there a reason why something similar to the following code that checks if the label is a stable isotope is not used?
```
...
names=data.data_names
for j in names:
    i=j[len(prefix):]
    isAbun=False
    if i in self.stable_isos:
        isAbun=True
    if isAbun and j[:len(prefix)]==prefix:
        abun_list.append(j)
...
```

**Comment by rjfarmer** [comment]
Interesting, the problem with using self.stable_isos, is that list only contains the stable isotopes, for instance self.stable_isos is missing ni56. Maybe we could do something with self.elementsPretty (the 1-2 character name of an element) but the easier thing will be to find why we loose the first character of an elements name (so there is bad index in the _listAbun could somewhere)

**Comment by OriolAbril** [comment]
The problem is that as between `center_` and `surface_` there is only a letter of difference in length, _listAbun uses "e4" or "e20" to see if they fit the format of an element, which they do. However, with the second condition `j[:len(prefix)]==prefix` that checks if the start of `j` is the same as the prefix, this problem could be solved.
Ah, and using regular expressions we could easily separate the characters from the numbers to check if the characters are in self.elements.

**Comment by OriolAbril** [comment]
I think that this code should do the work using regular expressions:
```
import re
patAbun=re.compile(r'^([a-z]{1,3})[0-9]') #match any lowercase alphabetical character at the start of the line with length between 1 and 3 and followed by a number (any number). The brackets are the part of the match to save
...
    i=j[len(prefix):]
    isAbun=False
    matchAbun=patAbun.match(i)
    if matchAbun:
        if matchAbun.groups(1)[0] in self.elements:
            isAbun=True
    if isAbun and j[:len(prefix)]==prefix:
    abun_list.append(j)
```
