### ISSUE TITLE
Forgotten 'prot' check in line 1900

### ISSUE THREAD

**Issue by OriolAbril** [rjfarmer/mesaplot#6]
At `_plotAbunPAndN` when checking for `'neut'` at line 1900, a check for `'prot'` is missing. Changing the line for the following one worked for me:
```
if (i == 'neut' or i == 'prot'):
```

**Comment by rjfarmer** [comment]
Thanks for catching that, though to handle cases where there is a prefix on the isotope name we should do:
if ''prot' in i or 'neut' in i:
