### ISSUE TITLE
_plotAbunPAndN mass_frac_rng unexpected behaviour

### ISSUE THREAD

**Issue by OriolAbril** [rjfarmer/mesaplot#8]
I have seen that P vs N plots do not distinguish between the elements with abundances over `max_col` and with abundances under `min_col`, as all the values that are not inside `mass_frac_rng` are represented with an empty square. Is this behaviour intentional? 

I wold expect different behaviours for elements over `mass_frac_rng` and beneath `mass_frac_rng` like being filled in black and being empty respectively or something like that.

**Comment by rjfarmer** [comment]
It was intentional, though i'm open to changes. Maybe empty squares for under and everything over should just get the max color?

**Comment by OriolAbril** [comment]
It can obviously be fixed without any problem by setting the range right, however, the first thought that came across my mind was that I was already doing something wrong. I think that everything over having the `max_color` would be more intuitive. I had thought of black as kind of a warning that the values were outside the colorbar range, but maybe it's better to give the warning some other way or to not give it at all.

**Comment by rjfarmer** [comment]
For me, the point of the upper limit on the mass_frac_rng is for when i want to "zoom" in on some mass_frac_range in which case it make sense to leave the squares blank as i don't care about those isotopes outside the range.

I'll add a flag to switch between behaviors then everyone can have what they want :)

**Comment by OriolAbril** [comment]
Great! Thanks a lot!

**Comment by rjfarmer** [comment]
fixed in  d2e93d5 

now you need to pass either  bounds= (to plotAbunPAndN) to change the behaviour
0: above and below mass frac rng is white
1: above and below get nearest color in colormap
2: below is white and above is black
